### ISSUE TITLE
TypeError when running theseus script on CellRanger Filtered H5 matrix file

### ISSUE THREAD

**Issue by SaraJeanne08** [asncd/schimera#1]
I am running the following command on 10X CellRanger v6.1 output filtered matrix h5 file: python2 /efs/analysis/compbio-common/software/schimera/theseus_10x.py  filtered_feature_bc_matrix.h5 /schimera_out/ 0.05 101770

And getting the error below:
('List of arrays in this file: \n', [u'matrix'])
reading file took 0.000237941741943
Traceback (most recent call last):
  File "/efs/analysis/compbio-common/software/schimera/theseus_10x.py", line 87, in <module>
    T = read_10x_h5(path2h5) 
  File "/efs/analysis/compbio-common/software/schimera/theseus_10x.py", line 41, in read_10x_h5
    TABLE['bcumi']=zip(bc,umi)
TypeError: zip argument #1 must support iteration

Note: I also tried this on the raw_feature_bc_matrix.h5 file as well and got the same error.

Could you help me figure out how to fix this issue? Thank you!

**Comment by asncd** [comment]
Hi Sara, you should be using this file instead "molecule_info.h5"

**Comment by asncd** [comment]
there are a few changes in the newest version of the .h5 format from 10x that still need to be incorporated

**Comment by SaraJeanne08** [comment]
Hi @asncd Atray, thank you for responding. I tried the molecule_info.h5 file but got the same error. I assume that this is due to formatting issues with the updated CellRanger h5 format?
